### ISSUE TITLE
Wob-Knop to Woo-Knop

### ISSUE THREAD

**Issue by gbp** [mysociety/wob-knop-theme#29]
New primary domain woo-knop.nl and secondary domain wooknop.nl

- [x] Point domains to mySociety's nameservers
- [x] Update theme help pages
- [x] Update logo
- [x] Update server DNS config
- [x] Update server email config
- [x] Update application config
- [x] Create redirects from "wob*" domains to canonical "woo" domain
- [x] Verify what will happen to emails received to the old domain - holding pen or will they get to the correct request
- [x] Social media accounts
- [x] Gmail support inbox address

**Comment by gbp** [comment]
On the servers repo there is a `wob-knop-to-woo-knop` branch with the DNS, email and application config changes.

@sagepe would you be able to take a look to see if I've set up the domain and email redirection correctly?

**Comment by sagepe** [comment]
That looks good I think; we'll need to ensure we've added the new domains to our secondary DNS service before we do the initial deploy.

**Comment by gbp** [comment]
This has been deployed and DNS and email redirection all seems to be working correctly now.
